Write-Host "Start the services in separate terminals:"
Write-Host ""
Write-Host "1. PHP web app"
Write-Host "   cd web"
Write-Host "   php -S localhost:8000 -t public"
Write-Host ""
Write-Host "2. ML service"
Write-Host "   cd ml-service"
Write-Host "   py -3.11 -m venv .venv311"
Write-Host "   .\.venv311\Scripts\Activate.ps1"
Write-Host "   pip install -r requirements.txt"
Write-Host "   uvicorn app.main:app --reload --port 8001"
